.POSIX:

# This Makefile was generated by maje
# See https://gitlab.com/jkaivo/maje/ for more information
# Do not edit this Makefile by hand

default: all

CC=c99
LD=$(CC)
CFLAGS=-Wall -Wextra -Wpedantic -Werror -g
LDFLAGS=

all: file

clean:
	rm -f file *.o

file: file.o
file.o: file.c
	$(CC) $(CFLAGS) -c file.c

file: magic.o
magic.o: magic.c
	$(CC) $(CFLAGS) -c magic.c

file:
	$(LD) $(LDFLAGS) -o $@ *.o
